team-elder-and-nikki/yes-chef-app

- .github/BUG_PULL_REQUEST_TEMPLATE.md
- .github/FEATURE_PULL_REQUEST_TEMPLATE.md
- .gitignore
This PR creates the .github directory to hold the Bug and Feature PR templates, and creates the templates.
> PR templates for bug and feature

- .gitignore
- app.js
- app.ts
- package.json
- install express package
- install body parser
- check if backend was setup correctly
> init backend setup

- package.json
added the following:
- version
- description
- name
- list of contributors with each element an object of contributor name and github profile link
> refine package.json

- README.md
- Add Sprint board schedule
- Update Table of content
> Sprint Board schedule README.md

- .github/user-stories.md
- README.md
- package.json
N/A
Contains both users stories and the acceptance criteria for three main users
> User stories Markdown Added to .gitHub file

- client/components.json
- client/package.json
- client/src/.src/components/ui/checkbox.tsx
- client/src/App.tsx
- client/src/components/ui/button.tsx
- client/src/index.css
- client/src/lib/utils.ts
- client/tsconfig.json
- client/vite.config.ts
Edit the import statement on App.tsx to "import { Button } from "@/components/ui/button";"
THEN
Add <Button></Button>
THEN
Run "npm run dev" from /client and a button will appear (in the upper left corner as a black button, see screenshot)
[Screenshot 2025-03-04 201442](https://github.com/user-attachments/assets/2184b502-0411-4290-9a27-7626b0f8473a))
Take the acceptance criteria from the issue and describe how the changes in the PR meets it.
shadcn installed
> CCS-68-setup-shadcn

- client/src/App.tsx
- client/src/components/ui/button.tsx
- update style for button shadcn component
- remove example button import component
- update start script file path for app.ts
> button component

- client/package.json
- client/src/components/ui/MenuCategoryNav.tsx
- client/src/components/ui/tabs.tsx
- client/src/pages/Menu.tsx
download shadcn tabs component
add MenuCategoryNav component 
add MenuCategoryNav component to the Menu page
> feat(menu): add menu category nav component

- client/src/App.tsx
- client/src/components/CartTable.jsx
- client/src/components/MenuItemTest.tsx
- client/src/components/ui/table.tsx
- client/src/context/CartContext.tsx
- client/src/pages/Menu.tsx
download shadcn table component
add CartTable component
add subtotal, tax and total to the bottom of the component
add Clear All button that clears the cart 
add SEND Button and test onClick event on
add context folder and CartContext.tsx file for updating CartTable state
wrap CartProvider around BrowserRouter in the App.tsx file to share cart state globally.
added dummy MenuItemTest.jsx and MenuItem component (also dummy) to test cart functionality
added MenuItem and CartTable components to the Menu page
> Cart component

- config/config.ts
- server/app.ts
- server/controllers/ingredient.ts
- server/models/Ingredient.ts
- tsconfig.json
update tsconfig file with noEmit and allowImportingTsExtensions
add ingredients controllers to fetch db data
add ingredient models and interface with types.
> feat: fetch ingredient route

- README.md
- package.json
- update installation instructions
- add command to run backend
- add command to run frontend
- update package.json start script path to handle app.ts nesting in server folder
> Read and package.json update

- client/package.json
- client/src/components/NavBar.tsx
- client/src/components/ui/navigation-menu.tsx
- client/src/pages/Inventory.tsx
- client/src/pages/Kitchen.tsx
- client/src/pages/Menu.tsx
- client/src/pages/Orders.tsx
- client/src/pages/Reports.tsx
Fire up the frontend and visit any page. Ensure the Navbar is on every page and it is responsive.
figma designs:
As a user of Yes-Chef, I should see a Navigation bar on the top or side of the screen that, when I click a nav option, it takes me to that page.
> Ccs 92 feat add app nav component

- package.json
installed concurrently and updated root start script
run npm i in root to install
run npm start in root to start client and server with 1 command
> installed concurrently and updated root start script

- client/src/components/MobileInventoryCard.tsx
- client/src/pages/Inventory.tsx
#161
Steps to Reproduce or Test
view inventory in mobile sizes and tablet+
Image or GIF of Expected Behavior
mobile:
tablet+:
> responsive rendering of mobile or tablet-desktop inventory views

- client/src/components/CartTable.jsx
- client/src/components/MenuCard.tsx
- client/src/components/ui/MenuCategoryNav.tsx
- client/src/components/ui/table.tsx
- client/src/components/ui/tabs.tsx
- client/src/pages/Menu.tsx
add responsive styling to MenuNavBar, MenuCard and CartTable. Updated hover and styling for delete button in the cart items.
disabled clearAll and send button if cart is empty.
add Sending... on Send button if isLoading is true.
> add responsive styling to MenuNavBar, MenuCard and CartTable. updated cart

- client/src/components/MobileInventoryCard.tsx
- client/src/components/ui/IncrementingInput.tsx
- client/src/models/Ingredient.ts
- server/models/Ingredient.ts
#164
Steps to Reproduce or Test
npm run start from root
navigate to inventory page in a mobile view
click to expand a row, update the stock with the up/down arrows and see that the stock number goes up or down
update the order qty with the up/down arrows and see that the total goes up and down
** If anyone is very good at aligning things - i cannot get the up/down chevron that comes with the accordian component from shadcn to be on the right of that 'cell' it's driving me insane but i can't figure it out. **
Image or GIF of Expected Behavior
> Ingredients mobile view - update stock and re-order qty

- client/src/components/CartTable.jsx
- client/src/context/CartContext.tsx
add Axios to work with POST request for orders from PR#43
add addOne and subtractOne functionality to items in the cart
> Cart axios update

- client/src/components/MenuCategoryNav.tsx
- server/controllers/ingredient.ts
- server/controllers/kitchen.ts
- server/controllers/order.ts
- server/models/Ingredient.ts
- server/models/Order.ts
- Updated timestamp logging to controller request handlers. This will help with tracking request times and debugging.
- Merged and added responsive styling for category navigation from diverged branch.
> fix: update timestamps in controller responses and add responsive styling to category nav

- client/src/models/Ingredient.ts
- client/src/models/Menu.ts
- client/src/pages/Reports.tsx
feat: add logic to determine money wasted based on the number of ingredients wasted
> ingredients wasted logic

- client/src/components/InventoryTable.tsx
- added form parent to input and button to trigger submit on pressing enter button
- Added prevent default to button to prevent automatic refresh on submission
- Reformatted styling to fit form in table cell parent into one line.
https://github.com/user-attachments/assets/7905722e-f306-45d3-848d-1016e8b65d53
src: https://stackoverflow.com/questions/155188/trigger-a-button-click-with-javascript-on-the-enter-key-in-a-text-box
> feat: trigger inventory onclick order buton on enter key press

- server/api/distributor/distributorController.ts
- server/api/distributor/distributorRoutes.ts
- server/api/distributor/distributorService.ts
- server/app.ts
CCS-135 - GET distributor API data 
This pull request adds functionality to fetch product distributor data. Further testing is needed to ensure proper API data retrieval. With this pull request we are able to:
- Grab data while accounting for failed fetch data
- Set up backup data for API going offline
- Handle API response and error scenarios
Futher updates required:
- Set up loading to account for fetching data
- Set up logic to account for API going offline
> feat: GET distributor API data

- client/src/components/InventoryTable.tsx
> Inventory Design Update- vertically center shopping cart icon, make inventory update box narrower

- client/src/components/KitchenCard.tsx
add toLocaleTimeString to display leading zero
> Kitchen card fix 2

- server/api/distributor/distributorController.ts
- server/api/distributor/distributorRoutes.ts
- server/api/distributor/distributorService.ts
- server/api/distributor/fallbackData.ts
- server/app.ts
**Description:**
- Implemented logic to handle failed fetch requests by including error handling.
- Added a check to detect if the API is offline and trigger a fallback mechanism.
- Set up backup data to use as a fallback when the primary API fetch fails.
**Changes Made:**
- Renamed 'product' to 'ingredient' to maintain consistency throughout app. 
- Added error handling around the API fetch request.
- Created a separate file for backup data to adhere to separation of concerns.
- Implemented a check to detect API downtime and switch to backup data.
These changes help to ensure robust data fetching and hande API downtime without disrupting functionality.
-Success responses: [
](url)
-Fallback response:
-Offline response
> feat: update and enhance API data handling and backup logic

- README.md
Updated README file to include necessary environment variables needed during installation - MongoBD connection string and Spoonacular API key.
> update README file to include environment variables

- client/src/components/ProfitabilityTable.tsx
- client/src/pages/Metrics.tsx
- server/controllers/ingredient.ts
- server/controllers/metrics.ts
You should be able to click on menu items from reporting dashboard and go to the table that returns the dishes profitability
Take the acceptance criteria from the issue and describe how the changes in the PR meets it.
Click on a dish and the metrics: cost of dish, ingredients, and profit are displayed on the bottom of the metrics table
> Metrics dashboard

- client/src/components/FilteredMenuItems.tsx
- client/src/context/CartContext.tsx
categories are rendering in kitchen cards
> add category property to Cart and filtered Items. issue #77

- server/controllers/ingredient.ts
- server/controllers/order.ts
- create and send a ticket to the kitchen
- advance that ticket through to "completed"
- inventory is automatically deducted when a ticket is completed.
> Automatic ingredient deduction

- client/src/components/CartTable.tsx
- client/src/components/InventoryTable.tsx
- client/src/components/ui/IncrementingInput.tsx
- Update last order date to dynamically generate dates to the user.
- Remove caption, add hover and animation to indicate to user that element is being hovered on.
> Update: Update inventory UI and UX

- client/src/components/CartTable.tsx
add breakpoints to the cart component, removed y padding
> add breakpoints to the cart height

- client/src/components/KitchenCard.tsx
> add vertical scroll, fix button to the bottom, add full width to the button

- client/src/components/ProfitabilityTable.tsx
- client/src/components/WasteTable.tsx
- client/src/pages/Metrics.tsx
> updated css for metrics page
